export const HOMEPAGE = '/'
export const LOGIN = '/login'
export const REGISTER = '/register'
export const RENTAL_APARTMENT = '/cho-thue-can-ho'
export const RENTAL_HOUSE = '/nha-cho-thue'
export const RENTAL_ROOM = '/cho-thue-phong-tro'
export const RENTAL_SPACE = '/cho-thue-mat-bang'
